#!/bin/bash

# Need to automate this step to set pw to be raspberry (like raspbian)
./set_shared_user_password.sh

./setup_board --board=rpi && \
./build_packages --board=rpi && \
./build_image --board=rpi --noenable_rootfs_verification

